#include "includes.hpp"

void BotDrawHommer(int sockfd, const std::string channel)
{
	std::string join_message = "PRIVMSG " + channel + " :▓▓▓▓\r\n";
    const char *str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▒▒▓▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▒▒▒▒▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG "+ channel + " :▒▒▒▒▒▒▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▒▒▒▒▒▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▒▒▒▒▒▒▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▒▒▒▒▒▒▓▓▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▓▓▓▓▓▓░░░▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▓░░░░▓░░░░▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▓░░░░░░▓░▓░▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▓░░░░░░▓░░░▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▓░░▓░░░▓▓▓▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▓░░░░▓▒▒▒▒▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▒▓▓▓▓▒▒▒▒▒▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▒▒▒▒▒▒▒▓▓▓▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▒▒▒▒▓▓▓▒▒▒▒▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▒▒▒▓▒▒▒▒▒▒▒▒▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▒▒▓▒▒▒▒▒▒▒▒▒▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▒▓▒▒▒▒▒▒▒▒▒▒▒▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▓▒▓▒▒▒▒▒▒▒▒▒▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▓▒▓▓▓▓▓▓▓▓▓▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▓▒▒▒▒▒▒▒▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
    join_message = "PRIVMSG " + channel + " :▒▒▓▒▒▒▒▒▓\r\n";
    str = join_message.c_str();
    send_command(sockfd, str);
}